# Generated by Django 4.1.6 on 2023-02-11 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meddata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Specalist/Dr')),
                ('address', models.CharField(max_length=300)),
                ('zip_code', models.CharField(max_length=15, verbose_name='Zip Code')),
                ('phone', models.CharField(blank=True, max_length=25, verbose_name='Contact Phone')),
                ('type', models.CharField(max_length=120, verbose_name='Specality')),
            ],
        ),
    ]
