# Generated by Django 4.1.6 on 2023-02-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meddata', '0002_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Childs Name')),
                ('dob', models.DateTimeField(verbose_name='Date of Birth')),
            ],
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='type',
            new_name='specialty',
        ),
    ]
