# Generated by Django 4.1.4 on 2023-02-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meddata', '0003_child_rename_type_doctor_specialty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Child',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='address',
            field=models.CharField(max_length=300, verbose_name='Address'),
        ),
    ]
