# Generated by Django 4.1.4 on 2023-02-16 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meddata', '0005_doctor_clinic_profile_age_profile_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='date_of_birth',
        ),
    ]
