# Generated by Django 4.1.4 on 2023-02-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meddata', '0007_doctor_user_profile_bio_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d/'),
        ),
    ]
