# Generated by Django 4.1.4 on 2023-02-18 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meddata', '0009_remove_profile_date_of_birth_remove_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calms', models.CharField(choices=[('yes', 'Yes'), ('not sure', 'Not Sure'), ('not yet', 'Not Yet')], max_length=10, null=True, verbose_name='Calms down when spoken to or picked up')),
                ('looks', models.CharField(choices=[('yes', 'Yes'), ('not sure', 'Not Sure'), ('not yet', 'Not Yet')], max_length=10, null=True, verbose_name='Looks at your face')),
                ('happy', models.CharField(choices=[('yes', 'Yes'), ('not sure', 'Not Sure'), ('not yet', 'Not Yet')], max_length=10, null=True, verbose_name='Seems happy to see you when you walk up')),
                ('smiles', models.CharField(choices=[('yes', 'Yes'), ('not sure', 'Not Sure'), ('not yet', 'Not Yet')], max_length=10, null=True, verbose_name='Smiles when you talk or smile to them')),
                ('sounds', models.CharField(choices=[('yes', 'Yes'), ('not sure', 'Not Sure'), ('not yet', 'Not Yet')], max_length=10, null=True, verbose_name='Makes sounds other than crying')),
                ('loud', models.CharField(choices=[('yes', 'Yes'), ('not sure', 'Not Sure'), ('not yet', 'Not Yet')], max_length=10, null=True, verbose_name='Reacts to loud sounds')),
                ('watches', models.CharField(choices=[('yes', 'Yes'), ('not sure', 'Not Sure'), ('not yet', 'Not Yet')], max_length=10, null=True, verbose_name='Watches you as you move')),
                ('toy', models.CharField(choices=[('yes', 'Yes'), ('not sure', 'Not Sure'), ('not yet', 'Not Yet')], max_length=10, null=True, verbose_name='Looks at a toy for several seconds')),
                ('head', models.CharField(choices=[('yes', 'Yes'), ('not sure', 'Not Sure'), ('not yet', 'Not Yet')], max_length=10, null=True, verbose_name='Holds head up when on tummy')),
                ('move', models.CharField(choices=[('yes', 'Yes'), ('not sure', 'Not Sure'), ('not yet', 'Not Yet')], max_length=10, null=True, verbose_name='Move both arms and both legs')),
                ('hands', models.CharField(choices=[('yes', 'Yes'), ('not sure', 'Not Sure'), ('not yet', 'Not Yet')], max_length=10, null=True, verbose_name='Opens hands briefly')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
