# Generated by Django 4.1.4 on 2023-02-24 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meddata', '0011_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='user',
        ),
        migrations.AddField(
            model_name='notes',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
